create table EXAM_ASSIGN_EMP_IDS as
SELECT DISTINCT A.EXMNR_ID,C.LAST_NAME,C.FIRST_NAME,C.DIVISION,B.EMP_ID,B.NME_LAST,B.NME_FIRST,B.NME_MIDDLE,B.NME_FULL,B.DIV_NAME
FROM EXAMS_ASSIGNMENTS A  JOIN EMP_LIST_TEMP C 
ON A.EXMNR_ID=C.EXMNR_ID
LEFT OUTER JOIN EP_DIRECTORY_MAIN B 
ON C.EXMNR_ID=B.EXMNR_ID 
OR (TRIM(B.NME_LAST)=TRIM(C.LAST_NAME) AND 
(C.FIRST_NAME=B.NME_FIRST||' '||B.NME_MIDDLE 
OR C.FIRST_NAME=SUBSTR(B.NME_FIRST,1,4)||' '||B.NME_MIDDLE 
OR C.FIRST_NAME=B.NME_FIRST||' '||B.NME_MIDDLE||'.' 
OR C.FIRST_NAME=B.NME_MIDDLE||'. '||B.NME_FIRST
OR C.FIRST_NAME=B.NME_MIDDLE||' '||B.NME_FIRST))
WHERE A.EXMNR_ID IS NOT NULL AND A.EXMNR_ID !='NULL' order by 5 asc;

SELECT distinct a.key_examination,a.id_examiner,
  b.id_target,C.INST_NUM,C.ID_EXAM,d.FK_ID_EXAM
FROM EXAMINATION_ASSIGNMENT a
JOIN examination b
ON A.KEY_EXAMINATION=B.KEY_EXAMINATION
LEFT OUTER JOIN exams_main c
ON b.id_target=C.INST_NUM
left outer join exams_review d
on c.id_exam=d.FK_ID_EXAM
WHERE a.id_examiner IN ('4737',
'4738',
'1782',
'1682');
